---
title: "Format UCSC cellbrowser"
author: "Kent Riemondy RBI"
date: "5/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cellbrowser

Format seurat object into a cellbrowser directory suitable for html browser. 

```{r}
source("../R/utils.R")
library(tidyverse)
sobj <- readRDS(file.path("objects", "sobj.rds"))
```

Simplify object metadata to make interpretable

```{r}
cols <- colnames(sobj@meta.data)
cols_to_keep <- c(
  `genes per cell` = "nFeature_RNA",
  `UMIs per cell` = "nCount_RNA",
  `percent of UMIs as mitochondria` = "percent.mt",
  `clusters` = "clusters",
  `sample` = "orig.ident",
  `cell cycle phase` = "Phase",
  `Tabula Muris cell type` = "tabula_muris_cell_type"
)
sobj@meta.data <- sobj@meta.data[, cols_to_keep]
colnames(sobj@meta.data) <- names(cols_to_keep)
Idents(sobj) <- "clusters"

```



```{r}
outdir <- "cellbrowser"
dir.create(outdir, showWarnings = FALSE)
# write out rds files with names listed in sobjs
saveRDS(sobj,file.path(outdir, "cb.rds"))
```

## Set colors

```{r}
## default palette (see ../../R/globals.R)
col_palette <- discrete_palette_default

## summarize per cluster annotations
to_map <- c("clusters",
            "sample",
            "Tabula Muris cell type",
            "cell cycle phase")
col_map <- as.list(sobj@meta.data[, to_map]) %>%
      map(~as.character(unique(.x)))

res <- list()

tmp <- col_palette[1:length(col_map$clusters)]
names(tmp) <- col_map$clusters
res$clusters <- tmp 

tmp <- col_palette[1:length(col_map$sample)]
names(tmp) <- col_map$sample
res$sample <- tmp 

tmp <- col_palette[1:length(col_map$`Tabula Muris cell type`)]
names(tmp) <- col_map$`Tabula Muris cell type`
res$`Tabula Muris cell type` <- tmp 

tmp <- col_palette[1:length(col_map$`cell cycle phase`)]
names(tmp) <- col_map$`cell cycle phase`
res$`cell cycle phase` <- tmp 


map_dfr(res, 
        ~tibble(clusterName = names(.x), 
                color = .x)) %>% 
  as.data.frame() %>% 
  write_csv("cellbrowser/colorMap.csv", col_names = F, quote_escape = "none")

```


Build cellbrowser objects. Note requires UCSC (`cellbrowser python package`[ https://cellbrowser.readthedocs.io/index.html])

```{r}
dir.create("cellbrowser/markers", recursive = TRUE)
cols <- colnames(sobj@meta.data)
names(cols) <- colnames(sobj@meta.data)
mkrs <- read_tsv("markers/per_cluster_markers.tsv") %>% 
  select(cluster, gene, p_val_adj, everything())

write_tsv(mkrs, "cellbrowser/markers/cluster_markers.tsv")

do.call(function(...) {ExportToCellbrowser(sobj, 
                    dir = file.path("cellbrowser", "ameloblast"),
                    dataset.name = "ameloblasts",
                    reductions = c("umap"),
                    markers.file = "cellbrowser/markers/cluster_markers.tsv",
                    cluster.field = "clusters",
                    ...)}, 
        as.list(cols))

```



```{bash}
cd cellbrowser
echo -e '\ncolors="/Users/kriemo/Projects/sc_repos/vanotterloo/results/cellbrowser/colorMap.csv"' >> ameloblast/cellbrowser.conf
```


```{bash}
cd cellbrowser
/miniconda3/bin/cbBuild \
  -i ameloblast/cellbrowser.conf \
  -o ablast
```





Add subset

```{r}
sobj <- readRDS(file.path("objects", "ablast_sobj.rds"))
cols <- colnames(sobj@meta.data)
cols_to_keep <- c(
  `genes per cell` = "nFeature_RNA",
  `UMIs per cell` = "nCount_RNA",
  `percent of UMIs as mitochondria` = "percent.mt",
  `clusters` = "clusters",
  `sample` = "orig.ident",
  `cell cycle phase` = "Phase",
  `Tabula Muris cell type` = "tabula_muris_cell_type"
)
sobj@meta.data <- sobj@meta.data[, cols_to_keep]
colnames(sobj@meta.data) <- names(cols_to_keep)
Idents(sobj) <- "clusters"

```



```{r}
outdir <- "cellbrowser"
dir.create(outdir, showWarnings = FALSE)
# write out rds files with names listed in sobjs
saveRDS(sobj,file.path(outdir, "cb_subset.rds"))
```

## Set colors

```{r}
## default palette (see ../../R/globals.R)
col_palette <- discrete_palette_default

## summarize per cluster annotations
to_map <- c("clusters",
            "sample",
            "Tabula Muris cell type",
            "cell cycle phase")
col_map <- as.list(sobj@meta.data[, to_map]) %>%
      map(~as.character(unique(.x)))

res <- list()

tmp <- col_palette[1:length(col_map$clusters)]
names(tmp) <- col_map$clusters
res$clusters <- tmp 

tmp <- col_palette[1:length(col_map$sample)]
names(tmp) <- col_map$sample
res$sample <- tmp 

tmp <- col_palette[1:length(col_map$`Tabula Muris cell type`)]
names(tmp) <- col_map$`Tabula Muris cell type`
res$`Tabula Muris cell type` <- tmp 

tmp <- col_palette[1:length(col_map$`cell cycle phase`)]
names(tmp) <- col_map$`cell cycle phase`
res$`cell cycle phase` <- tmp 


map_dfr(res, 
        ~tibble(clusterName = names(.x), 
                color = .x)) %>% 
  as.data.frame() %>% 
  write_csv("cellbrowser/colorMap_subset.csv", col_names = F, quote_escape = "none")

```


Build cellbrowser objects. Note requires UCSC (`cellbrowser python package`[ https://cellbrowser.readthedocs.io/index.html])

```{r}
dir.create("cellbrowser/markers", recursive = TRUE)
cols <- colnames(sobj@meta.data)
names(cols) <- colnames(sobj@meta.data)
mkrs <- read_tsv("markers/ablast_subset_cluster_markers.tsv") %>% 
  select(cluster, gene, p_val_adj, everything())

write_tsv(mkrs, "cellbrowser/markers/subset_cluster_markers.tsv")

do.call(function(...) {ExportToCellbrowser(sobj, 
                    dir = file.path("cellbrowser", "ameloblast_subset"),
                    dataset.name = "ameloblasts_subset",
                    reductions = c("umap"),
                    markers.file = "cellbrowser/markers/subset_cluster_markers.tsv",
                    cluster.field = "clusters",
                    ...)}, 
        as.list(cols))

```



```{bash}
cd cellbrowser
echo -e '\ncolors="/Users/kriemo/Projects/sc_repos/vanotterloo/results/cellbrowser/colorMap_subset.csv"' >> ameloblast_subset/cellbrowser.conf
```


```{bash}
cd cellbrowser
/miniconda3/bin/cbBuild \
  -i ameloblast/cellbrowser.conf \
  -i ameloblast_subset/cellbrowser.conf \
  -o ablast
```

