---
title: "Sexually dimorphic genes"
author: "Kent Riemondy RBI"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: cosmo
    highlight: tango
    fig_caption: true
    code_folding: hide
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r libs, message=FALSE, warning=FALSE, echo=FALSE}
source("../R/utils.R")
library(future)
plan(strategy = "multicore", workers = 4)
options(future.globals.maxSize = 2 * 1024 ^ 3)

proj_dir <- here()
data_dir <- file.path(proj_dir, "data", "cellranger")
doc_dir <- file.path(proj_dir, "docs")

fig_dir <- "figs"
mkrs_dir <- "markers"
walk(c(fig_dir,mkrs_dir), dir.create, showWarnings = F)
```

```{r}
sobj <- readRDS(file.path("objects", "sobj.rds"))
```

```{r dl_data}
ext_data <- file.path(proj_dir, "dbases", "tabula_muris")
x <- dir.create(ext_data, recursive = TRUE, showWarnings = FALSE)

urls <- c(
  "droplet_Tongue_seurat_tiss.Robj" = "https://ndownloader.figshare.com/files/13090877",
  "droplet_Bladder_seurat_tiss.Robj" = "https://ndownloader.figshare.com/files/13088531",
  "droplet_Kidney_seurat_tiss.Robj" = "https://ndownloader.figshare.com/files/13088849",
  "droplet_Liver_seurat_tiss.Robj" = "https://ndownloader.figshare.com/files/13089197"
)

names(urls) <- file.path(ext_data, names(urls))

iwalk(urls, download.file)

to_process <- names(urls)
names(to_process) <- str_split(basename(to_process),"_") %>%
  map_chr(~.x[2])

mkrs <- map_dfr(to_process,
    function(fn){
  load(fn)
  tiss <- UpdateSeuratObject(tiss)
  Idents(tiss) <- "mouse.sex"
  mkrs <- FindMarkers(tiss, ident.1 = "F", ident.2 = "M") %>% 
    rownames_to_column("gene")
  rm(fn)
  mkrs
}, .id = "tissue")

strongly_dimorphic <- mkrs %>% 
  filter((pct.1 > 0.50 & pct.2 < 0.10) | 
           (pct.2 > 0.50 & pct.1 < 0.10) | 
           (pct.1 == 0.000 | pct.2 == 0.000)) 

write_tsv(mkrs, "dimorphic_genes_tabula_muris.tsv.gz")
```