---
title: "Split ameloblast populations"
author: "Kent Riemondy RBI"
date: "2/19/2020"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: cosmo
    highlight: tango
    fig_caption: true
    code_folding: hide
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r libs, message=FALSE, warning=FALSE, echo=FALSE}
library(scbp)
library(Seurat)
library(tidyverse)
library(cowplot); theme_set(theme_cowplot())
library(here)
library(future)
plan(strategy = "multicore", workers = 4)
options(future.globals.maxSize = 2 * 1024 ^ 3)

proj_dir <- here()
data_dir <- file.path(proj_dir, "data", "cellranger")
doc_dir <- file.path(proj_dir, "docs")

fig_dir <- "figs"
mkrs_dir <- "markers"
walk(c(fig_dir,mkrs_dir), dir.create, showWarnings = F)

#Sys.setenv(RETICULATE_PYTHON = "")
# for louvain in monocle3
# reticulate::py_config()
 
#reticulate::use_python("/miniconda3/envs/py37/bin/python", required = TRUE)
#reticulate::use_condaenv("py37", required = TRUE)
Sys.setenv(RETICULATE_PYTHON = "/miniconda3/envs/py37/bin/python")
reticulate::import("louvain")
```

```{r}
sobj <- readRDS(file.path("objects", "ablast_sobj.rds"))
```

```{r}
#drop sexually dimorphic genes
to_drop <- c("Gm10709",
  "Xist",
  "Gm8797",
  "Rpl29",
  "Ddx3y",
  "Eif2s3y",
  "Sfrp2",
  "Tsix",
  "Erdr1")

sobj <- sobj[!rownames(sobj) %in% to_drop, ]
```

# Subset ameloblasts
```{r}
outdir <- "ameloblast_late_diff_only"

fig_dir <- file.path("figs", outdir)
mkrs_dir <- file.path("markers", outdir)
walk(c(fig_dir,mkrs_dir), dir.create, showWarnings = F)

library(harmony)
ameloblast_cell_types <- c("Klk4_late_ameloblast",
  "Mmp20_early_ameloblast",
  "Krt27_early_ameloblast",
  "Mmp20_ameloblast_progenitor")

so <- subset(sobj, subset = cell_type %in% ameloblast_cell_types) %>% 
  FindVariableFeatures(nfeatures = 2000) %>% 
  ScaleData(features = VariableFeatures(.)) %>% 
  RunPCA(npcs = 30) %>% 
  RunHarmony(group.by.vars = "sample") %>% 
  FindNeighbors(dims = 1:20, reduction = "harmony", k.param = 20) %>% 
   RunUMAP(dims = 1:20, reduction = "harmony", reduction.name = "harmony_umap", min.dist = 0.5) %>% 
  FindClusters(resolution = c(0.1, 0.2, 0.3, 0.4, 0.5, 0.7))

so$seurat_clusters <- NULL
cluster_cols <- str_subset(colnames(so@meta.data), "RNA_snn_res")

plot_harmony(so, cluster_cols)
so$refined_ameloblast_clusters <- so$RNA_snn_res.0.3
```


```{r}
to_plot <- c("sample", "Phase", "cell_type")

plts <- plot_harmony(so, to_plot, sorted = "random", .cols = palette_OkabeIto)
names(plts) <- to_plot
imap(plts, 
    ~save_plot(file.path(fig_dir, str_c("umap_by_", .y, ".pdf")),
               .x, 
               base_asp = 1.4))
plts
```

```{r}
p <- plot_cell_proportions(so, "cell_type", "orig.ident", cols = palette_OkabeIto) +
  labs(x = "",
       fill = "")

p 

save_plot(file.path(fig_dir, "cell_distribution_per_sample.pdf"),
          p,
          base_asp = 1.5,
          base_height = 5)
```

```{r}
library(presto)
mkrs <- wilcoxauc(so, "refined_ameloblast_clusters") %>% 
  filter(logFC > 0,
         padj < 0.05,
         pct_in > 10) %>% 
  group_by(group) %>% 
  arrange(padj, desc(logFC), .by_group = T)

write_markers_xlsx(split(mkrs, mkrs$group), 
                   file.path(mkrs_dir, "refined_ameloblast_clusters.xlsx"))

write_tsv(mkrs, file.path(mkrs_dir, "refined_ameloblast_clusters.tsv"))

```

```{r}
plts <- mkrs %>% 
  slice(1:12) %>% 
  split(., .$group) %>% 
  map(~plot_harmony(so, .x$feature) %>% 
        plot_grid(plotlist = ., nrow = 4, ncol = 3))


imap(plts, 
    ~save_plot(file.path(fig_dir, str_c("umap_cluster_", .y, "_markers.pdf")),
               .x, 
               nrow = 4,
               ncol = 3,
               base_asp = 1.2))

plts
```

```{r}
p <- plot_harmony(so, "cell_type", group = "sample")
save_plot(file.path(fig_dir, str_c("umap_celltype_split_by_sample.pdf")),
               p, 
               nrow = 1,
               ncol = 2,
               base_asp = 1.2)
```

```{r}
library(qs)
qsave(so, file.path("objects/ameloblast_late_diff.rds"))
```
# Subset epithelial

```{r}
outdir <- "ameloblast_early_diff_only"

fig_dir <- file.path("figs", outdir)
mkrs_dir <- file.path("markers", outdir)
walk(c(fig_dir,mkrs_dir), dir.create, showWarnings = F)

library(harmony)
ameloblast_cell_types <- c(
  "Krt17_progenitors",
  "Krt15_progenitors",
  "Tnc_quiescent",
  "Notch_quiescent",
  "Sfrp5_TA"
  )


so <- subset(sobj, subset = cell_type %in% ameloblast_cell_types) %>% 
  FindVariableFeatures(nfeatures = 2000) %>% 
  ScaleData(features = VariableFeatures(.)) %>% 
  RunPCA(npcs = 30) %>% 
  RunHarmony(group.by.vars = "sample") %>% 
  FindNeighbors(dims = 1:20, reduction = "harmony", k.param = 20) %>% 
   RunUMAP(dims = 1:20, reduction = "harmony", reduction.name = "harmony_umap", min.dist = 0.3) %>% 
  FindClusters(resolution = c(0.1, 0.2, 0.3, 0.4, 0.5, 0.7))

so$seurat_clusters <- NULL
cluster_cols <- str_subset(colnames(so@meta.data), "RNA_snn_res")

plot_harmony(so, cluster_cols)
so$refined_ameloblast_early_clusters <- so$RNA_snn_res.0.3
```


```{r}
to_plot <- c("sample", "Phase", "cell_type")

plts <- plot_harmony(so, to_plot, sorted = "random", .cols = palette_OkabeIto)
names(plts) <- to_plot
imap(plts, 
    ~save_plot(file.path(fig_dir, str_c("umap_by_", .y, ".pdf")),
               .x, 
               base_asp = 1.4))
plts
```

```{r}
p <- plot_cell_proportions(so, "cell_type", "orig.ident", cols = palette_OkabeIto) +
  labs(x = "",
       fill = "")

p 

save_plot(file.path(fig_dir, "cell_distribution_per_sample.pdf"),
          p,
          base_asp = 1.5,
          base_height = 5)
```

```{r}
library(presto)
mkrs <- wilcoxauc(so, "refined_ameloblast_early_clusters") %>% 
  filter(logFC > 0,
         padj < 0.05,
         pct_in > 10) %>% 
  group_by(group) %>% 
  arrange(padj, desc(logFC), .by_group = T)

write_markers_xlsx(split(mkrs, mkrs$group), 
                   file.path(mkrs_dir, "refined_ameloblast_early_clusters.xlsx"))

write_tsv(mkrs, file.path(mkrs_dir, "refined_ameloblast_early_clusters.tsv"))

```

```{r}
plts <- mkrs %>% 
  slice(1:12) %>% 
  split(., .$group) %>% 
  map(~plot_harmony(so, .x$feature) %>% 
        plot_grid(plotlist = ., nrow = 4, ncol = 3))


imap(plts, 
    ~save_plot(file.path(fig_dir, str_c("umap_cluster_", .y, "_markers.pdf")),
               .x, 
               nrow = 4,
               ncol = 3,
               base_asp = 1.2))

plts
```


```{r}
p <- plot_harmony(so, "cell_type", group = "sample")
save_plot(file.path(fig_dir, str_c("umap_celltype_split_by_sample.pdf")),
               p, 
               nrow = 1,
               ncol = 2,
               base_asp = 1.2)
```

```{r}
library(qs)
qsave(so, file.path("objects/ameloblast_early_diff.rds"))
```
